name: Project linting

# this is trigger CI on all kinds of branches and PRs
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run lint
        run: yarn run lint
